### add a Article:
POST http://localhost:8080/api/v1/articles/452
Content-Type: application/json
Authorization: bearer {{adminJWT}}

{
  "description": "@l234asdas22 wwww@l 234l",
  "content": "ww34wasdasw l22342",
  "title": "l w34wsadasdasdw lll 2l2342"
}
### add a tag to article:
POST http://localhost:8080/api/v1/tags/402
Content-Type: application/json
Authorization: bearer {{userJWT}}

{
  "name": "Tigers"
}

### get all articles:
GET http://localhost:8080/api/v1/articles
Authorization: bearer {{adminJWT}}

### add a article to category:
POST http://localhost:8080/api/v1/articles/452
Content-Type: application/json

{
  "description": "@lxzZZZczx wdddwww@l l",
  "content": "wwwddssZZZxzczxcedvw l",
  "title": "l www lsdxzZZZcxzcfsfsxzdsxzdll l",
  "tags": {}
}

### add a article  :
POST http://localhost:8080/api/v1/articles
Content-Type: application/json
Authorization: bearer {{adminJWT}}

{
  "description": "222s22@lxzczx wddZZZZZZZZdwww@l l",
  "content": "22s222wwwddssxzczxcedZZZZZZvw l",
  "title": "222s22l www lsdxzcxzcfsfZZZZZZZZsxzdsxzdll l",
  "imageData": [],
  "tags": {}
}

### get all articles:
GET http://localhost:8080/api/v1/articles

//get pages
### GET ALL Articles pagination:
GET http://localhost:8080/api/v1/articles?pageNo=1&pageSize=2&sortDir=asc

###
PUT http://localhost:8080/api/v1/articles/2056
Content-Type: application/json
Authorization: bearer {{adminJWT}}

{
  "description": "@wwwwwwwwwwwwwwwwww",
  "content": "worknowwww 22",
  "title": "wwwwwwwwwwwwww"
}

###
DELETE http://localhost:8080/api/v1/articles/1052
Authorization: bearer {{adminJWT}}

###register a user:
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json
Authorization: bearer {{adminJWT}}

{
  "username": "Mike3",
  "email": "Mike3@gmail.com",
  "password": "Mike3@gmail.com"
}


### Demo Authenticated user details:
GET http://localhost:8080/api/v1/auth/me
Authorization: bearer {{adminJWT}}

###login as admin:
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "Passw0rd1!"
}

###login as user:
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "user",
  "password": "Passw0rd1!"
}
