### add a Article:
POST http://localhost:8080/api/v1/articles/452
Content-Type: application/json
Authorization: bearer {{adminJWT}}

{
  "description": "@l234asdas22 wwww@l 234l",
  "content": "ww34wasdasw l22342",
  "title": "l w34wsadasdasdw lll 2l2342"
}
### add a tag to article:
POST http://localhost:8080/api/v1/tags/402
Content-Type: application/json
Authorization: bearer {{userJWT}}

{
  "name": "Tigers"
}

### get all articles:
GET http://localhost:8080/api/v1/articles
Authorization: bearer {{adminJWT}}

### add a article:
POST http://localhost:8080/api/v1/articles/452
Content-Type: application/json

{
  "description": "@lxzczx wdddwww@l l",
  "content": "wwwddssxzczxcedvw l",
  "title": "l www lsdxzcxzcfsfsxzdsxzdll l",
  "tags": {}
}

### get all articles:
GET http://localhost:8080/api/v1/articles

//get pages
### GET ALL Articles pagination:
GET http://localhost:8080/api/v1/articles?pageNo=1&pageSize=2&sortDir=asc

###
PUT http://localhost:8080/api/v1/articles/402
Content-Type: application/json
Authorization: bearer {{adminJWT}}

{
  "description": "@MIwMAX22",
  "content": "Somwf 22",
  "title": "Learwaaaa22"
}

###
DELETE http://localhost:8080/api/v1/articles/353
Authorization: bearer {{adminJWT}}

###register a user:
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json
Authorization: bearer {{adminJWT}}

{
  "username": "Mike3",
  "email": "Mike3@gmail.com",
  "password": "Mike3@gmail.com"
}


### Demo Authenticated user details:
GET http://localhost:8080/api/v1/auth/me
Authorization: bearer {{adminJWT}}

###login as admin:
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "Passw0rd1!"
}

###login as user:
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "user",
  "password": "Passw0rd1!"
}
