### add a Catagory:
POST http://localhost:8080/api/v1/categories
Content-Type: application/json
Authorization: bearer {{adminJWT}}

{
  "name": "Travelssshhsssssss",
  "articles": []
}

### add a article to category:
POST http://localhost:8080/api/v1/articles/303
Content-Type: application/json
Authorization: bearer {{adminJWT}}

{
  "title": "How AI is helping scientists protect birds",
  "description":" As bird numbers fall worldwide, scientists and birders are using algorithm-powered apps to gather valuable data about avian species.2",
  "content": "Somsssdcdsfs987sssawf 2s23"
}

###updateCatagoryName
PUT http://localhost:8080/api/v1/categories/152
Content-Type: application/json
Authorization: bearer {{adminJWT}}

{
  "name": "HistoryAndCulture"
}

### get all catgories:
GET http://localhost:8080/api/v1/categories
Authorization: bearer {{adminJWT}}

###
DELETE http://localhost:8080/api/v1/categories/402
Authorization: bearer {{adminJWT}}

